### ISSUE TITLE
Build directory structure?

### ISSUE THREAD

**Issue by DanielNScott** [EDmodel/ED2#155]
I'd like to change the build directory structure from /build/bin and /dbgbuild/bin to /build/bin and /build/dbgbin. Instead of having e.g. include.mk.opt.odyssey in both folders with redundant KIND options, we could have only one include file per platform and use the options as needed rather than hardcode option selection. Also, in both folders, virtually everything has the 'opt' tag, which doesn't really seem right. Finally, it seems like the real reason the seperation exists is for the storing of .o and .mod files, but we don't need the weird duplication of the Makefile, the shell scripts, and the includes to accomplish that.

**Comment by mpaiao** [comment]
Your suggestion for restructuring build makes perfect sense.  As you said, one of the reasons was to keep .mod and .o separated.  The other was to change the order of commands in rules.mk so in the debugging case the local copies wouldn't be removed – some debuggers won't work properly otherwise.  The order in dbgbuild/bin/rules.mk would work in both cases.

**Comment by DanielNScott** [comment]
Ok, great, thanks for the input.
