### ISSUE TITLE
MMEAN_SAPA_STORAGE_RESP_PY 

### ISSUE THREAD

**Issue by lucianainpa** [EDmodel/ED2#189]
Please,
Someone know what does MMEAN_SAPA_STORAGE_RESP_PY mean?
What is the correct interpretation for MMEAN_SMOIST_GG_PY?
What is the name of MMEAN_WSHED_WG_PY, MMEAN_WOOD_WATER_PY and MMEAN_QTHROUGHFALL_PY?
This variable is in the canopy: MMEAN_CAN_VPDEF_PY?
What it means: MMEAN_AF_DECOMP_PY and this MMEAN_A_OPEN_PY
Why this variable always has zero value MMEAN_LEAF_DROP_PY? Do you also find zero value for it?
I'm trying to calculate the mortality rate for each PFT, it is possible?

**Comment by crollinson** [comment]
For reference, you can figure out a lot of these variables by searching through ED2/ED/src/memory/ed_state_vars.F90.  Variables will have different prefixes (MMEAN, DMEAN, etc) and suffixes (_PY) etc, but the roots will be the same.  "MMEAN_" = monthly mean and "_PY" means at the polygon level instead of patch ("_PA")  or cohort ("_CO").  For instance, if you search tor "SAPA_STORAGE" the comments around line 507 will help you figure it out a lot.

To answer a couple of your specific variables:
 -- I believe "SAPA" refers to Aboveground Sapwood (below ground sapwood would be SAPB), so this is the amount of storage respiration in aboveground sapwood.  Note that sapwood is distinguished from heart wood, which is tracked as "DEAD" in ED.  There is no pool for standing dead or snag trees like you would typically find in field data where an entire individual is dead or alive.

This group has mostly to do with water (ties to moisture availability, energy transfers):
smoist = soil moisture water flux
wshed = water shed from leaves to ground 
qthroughflow = the rate of water falling through the canopy to the ground (will be less than your precip rate if depending on the leaf interception and water ponding capacity).
wood_water = amount of water stored in the wood
CAN_VPDEF = vapor pressure deficit in the canopy

A_OPEN has to do with how open the stomata are and the rates of transpiration and carbon assimilation
AF_DECOMP has to do with rates of decomposition

LEAF_DROP has to do with leaves being shed for deciduous trees.  In the summer, this should be 0.

If you're trying to calculate values with for PFTs, you'll need to work with the COHORT level output ("_CO").  To get these values, you may need to adjust the settings in your ED2IN as this greatly increases the file size for each file your writing.  Depending on what you want, you may also need to dig into the guts of ed_state_vars.F90 to make sure it writes out the variables you're interested in.  I think there are some variables for mortality that are not being written out by default.

**Comment by crollinson** [comment]
I'll also warn you to remember that if you're aggregating cohort-level output in a multi-patch run to get a site/polygon-level value, you'll need to make sure you use weighted means.  For example, if you want to know the total AGB for PFT 8, it's the sum of AGB for that cohorts that are PFT 8, then you multiply that number by the area of that patch, and then you sum across patches.    Also be careful about the units because certain values are per individual in which case you need to multiply them by the density ("nplant").  Again, root around in ed_state_vars.F90 for leads on what the units are if they're not in the metadata that's written into the HDF5 output.

(Someone tell me if I'm wrong, but I think that's what I've done.)

**Comment by lucianainpa** [comment]
Thank you @crollinson

**Comment by xiangtao-princeton** [comment]
@lucianainpa I'm closing this issue since it is resolved
