### ISSUE TITLE
Meaning of units for monthly and daily GPP, NPP outputs

### ISSUE THREAD

**Issue by panditk17** [EDmodel/ED2#209]
I am having difficulty to interpret the units for these flux outputs from ED 2.1. DMEAN GPP (daily) has KgC/m2/yr unit and MMEAN GPP (monthly output) also has same unit (KgC/m2/yr). In the first place, I am not exactly sure what these units mean for each of these outputs. Secondly, I wanted to calculate annual KgC/m2/yr from these outputs, and don't know how to calculate it.

I appreciate your help on this matter.

**Comment by mdietze** [comment]
If you're outputting both the daily and monthly outputs, the easiest way to get the annual mean GPP would be to just take the mean of the daily GPPs. If you have the monthly outputs you technically need to take a weighted mean, since not all months have the same number of days.

Not sure about your first question, the mean flux (which is a rate, not a sum) has units that don't depend on the time period being averaged over. Personally, my group tends to convert to kgC/m2/s since those are the SI units, but again the units are the same whether you're talking about a single 30 min or multiple years.

**Comment by panditk17** [comment]
Michael, thank you for your response. I got answers for both of my questions abovee. I was getting very low GPP numbers for grass which led to this confusion. I would now check other components of my model simulation which might have impacted my low numbers.

**Comment by xiangtao-princeton** [comment]
@panditk17 I'm closing this issue since it is resolved
