### ISSUE TITLE
Initialization Modes

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#252]
Does anybody use anything other than IED_INIT_MODE=3 for initializing?  While debugging #251 I thought initializing in a different way worked, but as far as I can tell option 2 doesn't actually read the cohort information (I get 4 patches, but 0 cohorts ever grow).  

Option 3 however, appears to have some sort of bug that interacts with the hydrology driver and causes hydrology fails that I don't get if I restart from a history file in the same year.

**Comment by xiangtaoxu** [comment]
I have used IED_INIT_MODE=0 and 6, both of which worked fine for me.

Option 2 uses the old PFT numbers, if you want to use the PFT supplied from .css file as they are, you should use option 6

**Comment by mpaiao** [comment]
I only use options 0 and 6 too.  Option 6 only uses nplant, PFT and DBH from css files.  It then calculates height, balive and bdead using the allometry.  

I'm only mentioning this because I have the impression that some of the earlier IED_INIT_MODE options (1, 2, and 3) only used bdead from the css files and then it calculated DBH.

**Comment by crollinson** [comment]
0 works for me, but both 2 & 6 are having something go wrong when loading cohorts and I end up with none. With option 3 it load 475 cohorts which get condensed to 143.  With both options 2 & 6, the simulation starts with 0 cohorts and a check of some output confirmed that nothing grows.  It does load the patches okay.

For reference, my [.css file](https://github.com/crollinson/MetDownscaling_Manuscript/blob/master/ED_runs/0_setup/US-WCr.Inv.lat45.5lon-90.5.css) has info for DBH, PFT, & density, so maybe you have it backwards that on what uses biomass versus dbh?

I have confirmed that the TOPMODEL hydrology should not be used with the current version of ED.  It's also worth noting that if you initialize the model from a HISTORY file, TOPMODEL will not be used, even if it was used in the runs that generated the history file.

**Comment by crollinson** [comment]
If I send cases 2 & 6 to the same case as 3 [here](https://github.com/EDmodel/ED2/blob/5c785c6005ff7c1655c8dcb07822d9ebeda5bfe5/ED/src/io/ed_read_ed10_20_history.f90#L317-L348), then it loads cohorts correctly.  Is there a reason we can't or shouldn't combine 2, 3, & 6 here since the case works?

Also worth noting: cases 3 & 6 result in the same number of patches & cohorts being loaded (4 patches, 475 cohorts); option 2 is skipping a patch (3 patches, 260 cohorts).

**Comment by mpaiao** [comment]
I haven't used option 2 for many years, but option 6 definitely uses [DBH](https://github.com/EDmodel/ED2/blob/5c785c6005ff7c1655c8dcb07822d9ebeda5bfe5/ED/src/io/ed_read_ed10_20_history.f90#L759), not bdead.  

Also, there may be a difference in the contents of the pss/css files depending on the IED_INIT_MODE.  IED_INIT_MODE = 1 is supposed to be compatible with ED-1.0 output, and IED_INIT_MODE = 2 is supposed to match ED-2.0 (pre-HDF5 days) output.  Option 6 is somewhat similar to these options, except that the PFT numbers are the same as in ED2 (old ED versions had different numbers for the PFTs), but otherwise it has the same format. 

I am attaching an example of pss/css files formatted for IED_INIT_MODE=6, because I think the columns are slightly different depending on the option.  I appended the txt extension to upload it here.
[fst_default.lat-1.618lon-56.222.css.txt](https://github.com/EDmodel/ED2/files/2115975/fst_default.lat-1.618lon-56.222.css.txt)
[fst_default.lat-1.618lon-56.222.pss.txt](https://github.com/EDmodel/ED2/files/2115976/fst_default.lat-1.618lon-56.222.pss.txt)

**Comment by crollinson** [comment]
thanks @mpaiao!  After lots of varied attempts, I think I finally got my headers right and it seems to read things in correctly.   

@mdietze, you may want to be aware that these issues were discovered when trying to read the exiting Willow Creek .css, .pss files from PEcAn. I think most of the past workflows I have from Dietze Lab will need to be updated to work with the current ED2 mainline.  I haven't checked to see if anybody had updated the ED .css/.pss workflows in PEcAn recently, but just want to make sure this is noted.

**Comment by femeunier** [comment]
Hi @crollinson, @xiangtaoxu, @mdietze and @mpaiao ,

What I grasp from this issue and some others related to it (#251 ) is that IED_INIT_MODE=3 is now incompatible with the ED2 main line and we should use IED_INIT_MODE=6 instead. Is that correct? Just asking because I do have some similar problems (water budget related, see #251 ) when running ED2 with IED_INIT_MODE=3 and the water hydraulics. Did you guys spot the problem more precisely? I could easily switch to IED_INIT_MODE=6 but folks at BU seem to have used IED_INIT_MODE=3 for years with no problem ...

**Comment by mpaiao** [comment]
@femeunier I have never used TOPMODEL, so I can't comment on whether it's working or not with the current ED-2.2 (@crollinson indicated that it is not working earlier in this thread).   For the initialization question, the pss/css format is probably different between IED_INIT_MODE=3 and IED_INIT_MODE=6. Also, if I remember correctly, IED_INIT_MODE=3 may require renumbering the tropical PFTs in the css file.  I suggest checking ED/src/io/ed_read_ed10_20_history.f90 to see how you should write this.

All these options are in the code for historical reasons: IED_INIT_MODE=1 reads output from ED-1., IED_INIT_MODE=2 reads output from ED-2.0.  I don't think a lot of people are running ED-2.2 from actual output from ED-1.0 and ED-2.0 these days (and I don't think it'd be wise to do so as the models are so different).  One option would be to simplify all these options to a single pss/css format.  And if anyone has a reason to initialize the model from ED-1/ED-2 output, they could reformat their pss/css files before running ED-2.2.

**Comment by crollinson** [comment]
Hey @femeunier, I have had to stop using IED_INIT_MODE=3/TOPMODEL when I do runs with the mainline.  I'm not sure why we the BU/Dietze group used 3 in the first place, but I suspect it's because we've generally just copied ED2INs from each other for years.  I'm not sure what version most BU folks are currently using, but when I was there, most were relying on older versions.  

I do think there were some very nit-picky header issues that I had to resolve when I migrated to using IED_INI_MODE=6.  If you need examples, I can dredge through my commit histories to ty and figure it out.  (It's probably in [this project](https://github.com/MortonArb-ForestEcology/MANDIFORE_modeling/commits/master).)

I never did trace down the problem fully because I got it to at least run and had to call that good for sanity's sake.

**Comment by xiangtaoxu** [comment]
@femeunier I have never run ED2 with IED_INIT_MODE = 3 (with TOPMODEL). Just out of curiosity, have you tried IED_INIT_MODE=3 without hydraulics? If the hydraulics induces the problem, it might be because the surface water storage now includes dynamics of stem and leaf internal water. I account for that in computing total water budget but maybe I missed something in the lsm_hyd.f90. I am happy to sit down with you and check the errors.

**Comment by mdietze** [comment]
> I'm not sure why we the BU/Dietze group used 3 in the first place
Because we created it and because it's the only variant that reads the .site file instead of just the .pss and .css. That said, it's clearly been years since I've had a chance to work on maintaining the features this enables (soil heterogeneity, lateral hydrology, microclimate lapse rates, impacts of slope and aspect on radiation, etc) and clearly no one else has done that either (i.e. changes were introduced elsewhere that broke these features and no one was running tests to realize that they'd introduced breaking changes). I'd love to see mode 3 fixed, but I don't have time to do that myself anytime soon.
