### ISSUE TITLE
Crashes in the second hour on July 1st

### ISSUE THREAD

**Issue by ashehad** [EDmodel/ED2#261]
Hi All,

I'm running a version of ED2 and it runs okay from 1st Jan but sometimes it crashes in the second hour on Jul 1st of the same year or in the second hour on Jul 1st of the second year. I'm running at Duke and Moisst sites. A few lines of error message is as follows:

Image              PC                Routine            Line        Source
ed_2.1-opt         0000000000AC53F4  Unknown               Unknown  Unknown
libpthread-2.17.s  00002BA533CE85E0  Unknown               Unknown  Unknown
ed_2.1-opt         00000000009074F4  therm_lib_mp_uext        5260  therm_lib.f90
ed_2.1-opt         000000000084FC32  calchydrosubsurfa         406  lsm_hyd.f90

When I looked at the therm_lib.f90 file, it seems there is an issue with this equation:
uefroz = (dryhcap + wmass * cice) * t3ple. 

I'm not sure if 'wmass' is becoming zero or NaN, and how to track some of the variables from the above eqn.  If anyone has any thoughts on this, please let me know. I started having this problem when I switched to centos7 OS on odyssey. 

Thanks,
Ashehad

**Comment by mpaiao** [comment]
@ashehad crashes at the beginning of the month are almost always a problem with some variable not being initialized properly when a new patch or new cohort is created.  It is unlikely to be a problem in the thermodynamics itself.  

The easiest way to spot the problem is to recompile the code with strict debugging flags (the compilation options for [KIND_COMP=C](https://github.com/EDmodel/ED2/blob/24e6df6a75702337c5f29cbd3f3fad90467c9a51/ED/build/make/include.mk.odyssey#L112) in [include.mk.odyssey](https://github.com/EDmodel/ED2/blob/24e6df6a75702337c5f29cbd3f3fad90467c9a51/ED/build/make/include.mk.odyssey#L112) is a good option).  This should make the code crash at the first floating point exception, likely to be the real cause of the error you are seeing.  This option is good for debugging but not for running the model for scientific uses (it's too slow).

**Comment by ashehad** [comment]
Thanks Marcos for your response, and following it up. So there was a bug in the code related to 'nsoil' inside subroutine updateWatertableBaseflow, where nsoil was not assigned any value.  In the mainline version (https://github.com/EDmodel/ED2/blob/24e6df6a75702337c5f29cbd3f3fad90467c9a51/ED/src/dynamics/lsm_hyd.f90#L988), nsoil is defined at the beginning of the sub-routine.  In the version I'm using, nsoil was assigned in the middle of the subroutine, after the first use right after the “!! Determine freeze” comment. So I added nsoil definition at the beginning of the subroutine, like the mainline and so I get no more crashes.
