### ISSUE TITLE
Inconsistency in mortality calculations?

### ISSUE THREAD

**Issue by xiangtaoxu** [EDmodel/ED2#262]
It seems the change of nplant is calculated as 1-exp(sum(-mort_rate)*time) while mortality litter fall is calculated as (1 - sum(-mort_rate) * time) * biomass. See code below
https://github.com/EDmodel/ED2/blob/24e6df6a75702337c5f29cbd3f3fad90467c9a51/ED/src/dynamics/structural_growth.f90#L181-L210

Here monthly_dlndt = sum(-mort_rate) * time. monthly_dndt = sum(-mort_rate) * time * nplant. Wouldn't this break conservation of carbon in the model?

**Comment by larsonej** [comment]
After looking at the code, I agree with Xiangtao. It should be a small error if the mortality is fairly low, but the litter should be calculated using an exponential as well.

On Fri, Nov 9, 2018 at 1:32 PM, Xiangtao Xu <notifications@github.com<mailto:notifications@github.com>> wrote:

It seems the change of nplant is calculated as 1-exp(sum(-mort_rate)*time) while mortality litter fall is calculated as (1 - sum(-mort_rate) * time) * biomass. See code below
https://github.com/EDmodel/ED2/blob/24e6df6a75702337c5f29cbd3f3fad90467c9a51/ED/src/dynamics/structural_growth.f90#L181-L210<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EDmodel_ED2_blob_24e6df6a75702337c5f29cbd3f3fad90467c9a51_ED_src_dynamics_structural-5Fgrowth.f90-23L181-2DL210&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=DvPnhYJUFOFyqYn-CymOqL3hvZqf-FOetCGip2ZADP4&s=oSPsDIduCYxo0vuUsjThfguFvgU2jatOB6R8XIEoGsM&e=>

Here monthly_dlndt = sum(-mort_rate) * time. monthly_dndt = sum(-mort_rate) * time * nplant. Wouldn't this break conservation of carbon in the model?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EDmodel_ED2_issues_262&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=DvPnhYJUFOFyqYn-CymOqL3hvZqf-FOetCGip2ZADP4&s=9rrMMGapcPfH0sC8FkjWrzDnAz85EIJxFY1iUruDjq4&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Af-5F4b3EWVXR4YQT-5FuC8PezTkRQ7jcMzUks5utcpOgaJpZM4YXTDT&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=uJsb92W0cPZc-WrMGDoJaYBpyra3HRxkJwvTFq8XI_s&m=DvPnhYJUFOFyqYn-CymOqL3hvZqf-FOetCGip2ZADP4&s=cO51LqljQyS60VHweuRO-49FX_7vk-SQFfjdB5gDB1k&e=>.



--
Erik Larson
Postdoctoral Fellow
Department of Organismic and Evolutionary Biology
Harvard University

**Comment by mpaiao** [comment]
@xiangtaoxu @larsonej it does cause problems, in fact I've been working on resolving many violations of carbon conservation in the code and this was one of them.  I still need to find time to merge with the mainline (which is now quite different from my branch), but in the meantime, you can check how I solved in [my branch](https://github.com/mpaiao/ED2/blob/ab72dfad148c5b83ec0f8200ba543cb4d29de370/ED/src/dynamics/structural_growth.f90#L292).  

By the way, variable monthly_dndt is a legacy from ED-2.0 and we should probably delete it to avoid further confusion.  Mortality rates use the monthly_lnndt for numerical reasons: dn/dt = - m * n and d ln(n)/dt = -m are conceptually the same, but the latter reduces the error when integrating the change in population.

**Comment by xiangtaoxu** [comment]
@mpaiao OK, that sounds right to me. We should probably sit down and start the merge after AGU...
