### ISSUE TITLE
Understanding Land Use drivers

### ISSUE THREAD

**Issue by crollinson** [EDmodel/ED2#263]
I'm trying to create new land use drivers and am a bit confused as to whether the grid fraction for disturbed area (e.g. clutime%landuse(13) and clutime%landuse(15) ) get used to determine disturbance rates or if it's purely based on the size and harvest probabilities specified in the header.  I'm mostly looking at disurbance.f90 lines 1452-1581.  I see that in the case of plantation or logging of primary forest, the area from primary to secondary (column 11) us used, but not fraction area harvested on primary/secondary land.

From my understanding, it thought these would be used if the values in landuse(12) and landuse(14) were less < 0.  Are 13 & 15 used somewhere in the creation of new patches that I'm just not seeing?  If not, is it something that needs to be implemented?

@mpaiao the current mainline is laid out different than yours, but I think most of the functionality is the same.  Do you have any insights?   

@mdietze FYI, I'm working on a script to create an LU driver that will probably be of use to Pecan, so if you have any thoughts of what needs to be translated to build harvest scenarios for ED, let me know.

**Comment by mpaiao** [comment]
@crollinson As far as I remember, columns 13, 15, 17, 19 have never been used in ED-2. The model assumes that the disturbed area is proportional to the harvested biomass, from columns 12 and 14 (the rationale is that you need to log a larger area to meet the biomass demand). 

I can see reasons to set the area as opposed to the target biomass: depending on the land use driver, you may have the area and not the biomass.  I had a similar problem about 10 years ago when I was trying to use a scenario for the Amazon;  back then I made the flag for when 12 and 14 were negative.  If I remember correctly, back then I made a simple rule that would essentially log everything above the minimum DBH if the patch was older than a certain age.  It makes total sense to replace this extreme rule with using the grid fraction to tell how much area can be disturbed, although I would still impose that the area to be logged must be above a minimum age, to be set by the user.

**Comment by crollinson** [comment]
so if I'm understanding correctly, you vote for transforming the negative flag to going by area?  The other option would be to build in another ianth option where say if IANTH=3 (reserving 2 for eventually implementing your option for #2), then you do harvest by fraction area.

I think doing the negative flag makes sense since I'm not sure you'd do both biomass AND area, but I want to make sure I don't screw up anybody's current usage.

**Comment by mpaiao** [comment]
I don't think we need another option in IANTH, feel free to replace the negative number with the grid fraction.  When I generated the files with negative flag, I always put -1, so even if someone is using these old drivers for the Amazon (very unlikely), nothing would change for them because it would still apply logging over the entire area, assuming that you define relative area.  Yes, we definitely need to account for minimum patch age and minimum size for each PFT — at least in the tropics, there may be reasons to log some PFTs but not others.

Controlling for both biomass and area is not a good idea, biomass and area would need to be consistent between the land use driver and ED2, which is unlikely if the driver is not specifically built for ED (e.g. the drivers George Hurtt developed for CMIP6).

I am planning to eventually merge my code, but my branch is now quite different to the mainline, so I need time to make sure the merge doesn't cause troubles to others.
