### ISSUE TITLE
exceedingly warm topsoil and leaf temperatures 

### ISSUE THREAD

**Issue by larsonej** [EDmodel/ED2#304]
Hi All,
I wonder if anyone has come across this before. I am running ED2 in the Arctic/Boreal and the model is occasionally crashing due to high soil temperatures (topmost soil layer) or leaf temperatures. I am using a peat soil type near the surface and have tried modifying the albedo to reduce radiative heating. This problem only exists in a few grids of regional simulations, but I worry that it indicates a more general problem. Any thoughts?
[out_ED2_soiltemp.txt](https://github.com/EDmodel/ED2/files/4231986/out_ED2_soiltemp.txt)
[out_ED2_leaftemp.txt](https://github.com/EDmodel/ED2/files/4231987/out_ED2_leaftemp.txt)

**Comment by xiangtaoxu** [comment]
I had similar problem in the tropics when starting with a near-bareground. One thing I notice is that these extreme high temperatures happen when canopy air space temperature becomes really high (in your case ~ 320-330K) so that energy flow from leaf/soil to air in sensible heat is really low. When this is coupled with a mild drought, the model can crash.

Sometimes it can be ameliorated by reducing timestep to increase the radiative cooling but not always.

My feeling is that the energy balance of the canopy air space should be the ultimate cause of such problems but not sure what would be the best way to solve it...

**Comment by mpaiao** [comment]
Most of the time this happens when radiation is too high for the sun zenith angle.  This does not seem to be the case in your simulation as the crash did not happen near sunrise or sunset hours (at least based on the sun zenith angle in the output). 

I noticed that u* is almost at minimum at both crashes, which suggests lack of mixing. You could try increasing ustar_min to something like 0.1m/s. Also, would you mind uploading the ED2IN? I will try to take a look later.

**Comment by larsonej** [comment]
Thanks for the comments. You were both onto the problem. After I posted I tried changing a number of ED2IN settings. Doubling the minimum wind speed stopped the model from crashing. Also, changing the similarity theory model, ISFCLYRM, to 4 fixed the problem, as did changing the time step. I'm going to leave the minimum wind parameters doubled for these simulations.
