### ISSUE TITLE
'Total SW doesn't make sense' [need help!]

### ISSUE THREAD

**Issue by Lo-hatch** [EDmodel/ED2#324]
it shows that the 'rshort' (~1700) > 'rshort_max' (1500)
However, I check the met file in the Harvard met dataset (https://github.com/rgknox/edts-datasets/tree/master/met), and no SW data in any year-month exceed the maximum (1500).
Is it possible that the problem occurs when interpolating radiation between the integral hours?
![微信图片_20210310170551](https://user-images.githubusercontent.com/29476338/110604316-e759e980-81c2-11eb-813d-4412b9d82de6.png)

**Comment by Lo-hatch** [comment]
Please help me!

**Comment by mpaiao** [comment]
Just to clarify a few things for future reference:
1. Unless if you are using [NL%IMETAVG=-1](https://github.com/EDmodel/ED2/wiki/ED2IN-namelist#ed2in_imetavg) (which is deprecated), ED2 interpolates relative radiation instead of total radiation, to reduce radiation biases at noon or to prevent direct radiation before sunrise or after sunset (so for radiation the interpolation is not linear). For this to work properly, it is critical to know if the met driver time stamp corresponds to the beginning, middle, or end of the average period, and set  [NL%IMETAVG](https://github.com/EDmodel/ED2/wiki/ED2IN-namelist#ed2in_imetavg) accordingly.  Also, the time stamp should always be in UTC, not local time.
2. Indeed most [NL%IMETRAD](https://github.com/EDmodel/ED2/wiki/ED2IN-namelist#ed2in_imetrad) options add the met driver radiation components and find the fractions of direct/diffuse and visible/NIR radiation.  Unless the code has bugs, these fractions should always add up to 1, so it is unlikely that NL%IMETRAD is the culprit.

**Comment by xiangtaoxu** [comment]
I checked your met driver, it seems the Rshort (sum of vddsf, vbdsf, nbdsf, and nbdsf) is wrong for May 16th, likely because the time was not transformed to UTM time and used local time. See below

![image](https://user-images.githubusercontent.com/2780591/110964723-79780400-8321-11eb-9134-8d1c64165e51.png)

The interpolation based on solar zenith angle will then lead to abnormal radiation.

I know you are using old me files from Ryan Knox but apparently, this met file has problems. If you just want to have a test run, then just use meteorological data before 2007. Otherwise, I would recommend generating your own met files following the instructions [here](https://github.com/EDmodel/ED2/wiki/Drivers)
