### ISSUE TITLE
IMETAVG setting for NCEP/NCAR reanalysis

### ISSUE THREAD

**Issue by koxingazhu** [EDmodel/ED2#328]
Hi, everyone,
Who knows how to set IMETAVG if NCEP/NCAR reanalysis met data were used in ED2?
Do NCEP/NCAR reanalysis are in UTC? Do we need to set ITIMEA and ITIMEZ in ED2IN (default value was 0000)?

**Comment by mpaiao** [comment]
I haven't used NCEP reanalyses for a very long time, and to be honest I don't remember what was their default regarding the averaging, but they are definitely in UTC. I quickly checked the NCEP website and their papers on BAMS, but I couldn't find any information about the time averaging.

In case your research question is not tied to using NCEP reanalysis, I suggest considering ERA5 or MERRA2 instead, which have higher resolution and tend to be less biased.

ITIMEA and ITIMEZ are just the time of the day the model simulations will start.  The code should handle any initial time, but I'd recommend keeping them as 0000 (00 UTC), because the some processes in ED2 are only solved once a day (at 00 UTC).

**Comment by mpaiao** [comment]
@koxingazhu I have R scripts that process both ERA5 and MERRA2, I will upload them to my GitHub and let you know.  Just beware that they may be a bit too convoluted because I wrote them in a rush.

**Comment by mpaiao** [comment]
I uploaded the MERRA2 scripts to [my GitHub](https://github.com/mpaiao/ED2_Support_Files/tree/master/reanalysis_processing/MERRA2).  I will make the WFDE5 scripts (bias-corrected ERA5) soon, still working on it.

**Comment by mpaiao** [comment]
By the way, for MERRA2, NL%IMETAVG should be 3.

**Comment by koxingazhu** [comment]
@mpaiao Thank you so much!

**Comment by mpaiao** [comment]
I also uploaded the scripts to pre-process WFDE5 reanalyses (check [here](https://github.com/mpaiao/ED2_Support_Files/tree/master/reanalysis_processing/WFDE5).  WFDE5 should use NL%IMETAVG=2, as their time stamps correspond to the beginning of the average time.

**Comment by mpaiao** [comment]
@koxingazhu In case you already pulled the scripts, there was a minor bug when producing the header files. I updated both scripts.  I will also close the issue as this seems to be resolved, ok?

**Comment by koxingazhu** [comment]
@mpaiao I have downloaded these scripts and try to run it. I also found the bug in codes where creating met header file (maybe Lines 8-22 in header file? Variable types recognized by ED) and I will try to fix it. Please closed the issue. Thank you again for explaining IMETAVG setting and sharing the code.

**Comment by mpaiao** [comment]
Yes, this was the bug (the flags should be all written in a single line).  Also the precipitation flag should be 0, not 2.  I just pushed this additional fix to my repository.  If you find any additional bug, please feel free to make a pull request to my repository.
