### ISSUE TITLE
Debug Build Compilation Error

### ISSUE THREAD

**Issue by DanielNScott** [EDmodel/ED2#86]
I just updated my code to the most recent mainline and the debug executable doesn't compile...

Can someone verify they have the following issue as well?

```
/bin/cp -f ../../src/init/ed_init.F90 ed_init.F90
mpif90 -c -DUSE_INTERF=0 -DUSENC= -DPC_LINUX1 -DUSE_HDF5=1 -DUSE_COLLECTIVE_MPIO=0 -DUSE_MPIWTIME= -FR -O0 -recursive  -check all -g -debug extended -debug-parameters used -fpe0 -no-ftz -traceback -ftrapuv -fp-stack-check -implicitnone -assume byterecl -warn unused -warn uncalled -warn usage -warn interfaces -static  -I../../src/include -I/n/sw/hdf5/hdf5-1.8.2_intel-11.0.083/include   -DRAMS_MPI ed_init.F90
ed_init.F90(79): remark #7712: This variable has not been used.   [NPOLY]
   integer                    :: npoly
---------------------------------^
ed_init.F90(131): error #8055: The procedure has a dummy argument that has the ALLOCATABLE, ASYNCHRONOUS, OPTIONAL, POINTER, TARGET, VALUE or VOLATILE attribute. Required explicit interface is missing from original source.   [CGRID]
         call soil_default_fill(cgrid,ifm,ipy)
--------------------------------^
compilation aborted for ed_init.F90 (code 1)
make[1]: *** [ed_init.o] Error 1

```

It looks like the inclusion of the compiler flag -warn interfaces and the exclusion of -gen-interfaces is to blame... Is this intentional? Is there some reason we should not have the flag -gen-interfaces applied?

**Comment by mpaiao** [comment]
@DanielNScott I've seen this before and this is something we will need to fix eventually, though it will require substantial changes in the code. Newer compilers don't like objects of type pointer/target as arguments (e.g. cgrid, cpoly...), unless the subroutine is declared inside a module.  There are two possible long-term solutions I can think:
1.  Add modules to all routines that have cgrid, cpoly, etc..  This may be unfeasible if we have module A using module B, and module B using module A.
2.  Replace cgrid, csite, etc. by the indices ipy, isi, etc., then create the pointer locally.   

For a short-term "solution", you can pretend that the problem doesn't exist:
1. If you compile with ifort, you may be able to use the ifeq ($(KIND_COMP),C) block that is available in include.mk.opt.odyssey.
2. If you use gfortram check the ifeq ($(KIND_COMP),A) block in include.mk.opt.embrapa. I think the option that does the trick is -fno-whole-file, but it's been a while since I compiled with gfortran.

**Comment by DanielNScott** [comment]
Changing warn interfaces to gen-interfaces is a work-around... I'm going to push a commit to the mainline doing this.

**Comment by fabeit** [comment]
I am having the same issue but I didn't quite understand what parameters to change, @DanielNScott  where can I change interfaces? @mpaiao are you suggesting to remove or add -fno-whole-file? I am using the --system gfortran.

**Comment by mpaiao** [comment]
@fabeit I was suggesting to add -fno-whole-file.  But this option may no longer work depending on the gfortran version you are using.

**Comment by fabeit** [comment]
@mpaiao I solved the problem by using ifort, thanks anyway
