### ISSUE TITLE
ED2 Wiki - XML parameter file info doesn't [always] load

### ISSUE THREAD

**Issue by serbinsh** [EDmodel/ED2#89]
@mdietze @robkooper 

It seems that the ED2 Wiki page for the XML parameter file doesn't always load: https://github.com/EDmodel/ED2/wiki/Model-parameters-and-xml-parameter-files

Can we instead convert this to a PDF as well as a wiki page?  That way we could download a PDF version of the info to have on hand?

@Viskari

**Comment by serbinsh** [comment]
@mdietze Do you still have an old version of this wiki?  Or do we have other docs that I can look at to find the fission/fusion options?

**Comment by mdietze** [comment]
The trouble loading is just due to the size of the tables -- all the info is there but it renders it anew every time, so sometimes it stalls. The solution is just to split the info up into a larger number of tables, it just hasn't been a priority. The old wiki's sitting on a hard drive that's not attached to a computer, so that'd be even more work.

**Comment by mdietze** [comment]
I just moved the PFT-level parameters, which was the largest table, to it's own page so both this page and the remainder of the original page should be rendering quicker now. I'm having no problem accessing either

**Comment by serbinsh** [comment]
OK.  I think we can close
