### ISSUE TITLE
Growth/Storage Resp. Sources

### ISSUE THREAD

**Issue by DanielNScott** [EDmodel/ED2#92]
Growth and storage respiration appear to make up substantial fractions of ecosystem respiration in temperate sites. The image below illustrates respiration composition from a simulation of Harvard Forest spanning June of '10 to January of '13... 

![pso_7_ref_resps](https://cloud.githubusercontent.com/assets/7492269/8441269/050eda3a-1f2c-11e5-98f0-c465a4406eac.jpeg)

I'm of the opinion that storage respiration simply should not exist, but putting that aside for a moment it seems like treating storage and growth respiration as "wood flux" is probably not the best approximation.

If nothing else storage respiration should probably be partitioned into above and below-ground components, presumably on the basis of pft allometry/actual biomass, and I would be inclined to say the same for growth respiration given that we don't have a mechanistic way of accounting for it yet. Even better (in my opinion) would be actually creating bole-respiration, and rolling growth and storage resp into leaf / root / bole resp so that "actual" plant structures' respiration fluxes sum to the total plant respiration...

This may also partially resolve the problem that root respiration and heterotrophic respiration, at HF at least, don't come anywhere near the hypothetical ~40/60 split people talk about:

![r_soil_fractions](https://cloud.githubusercontent.com/assets/7492269/8441865/f173a470-1f2f-11e5-9fdc-fe9b550f41cd.jpg)

Oh yeah, and while we're talking about this, can we please nuke virtual leaf respiration? I guess it's a separate issue but evidence for our ability to do so mostly-side-effect-free is above...

Thoughts?

**Comment by mdietze** [comment]
I 100% agree with Dan that we should nuke virtual leaf respiration. I think we should nuke storage respiration as well. Neither exist as real biological processes. My lab has long been using the XML files to set storage respiration to 0 and to turn growth respiration back on for hardwoods with no negative effects. I wasn't around when storage respiration was added, but on reading David's thesis and early papers, I think add Rs was done because winter respiration was too low and was compensating for two other errors: 1) the snow was too dense and 2) root respiration was too low. Too dense snow leads to too hard a freeze of the soil in the winter which leads to root and soil respiration that are too low in the winter. The snow density problem was solved years ago and the empirical data in our meta-analyses suggest the default root respiration parameter is low (though admittedly there's a lot of variability in these numbers, as well as a lot of uncertainty about what's root vs rhizosphere). Storage respiration compensated for low winter Re in a non-physiological way (which growth respiration couldn't because there's no GPP in the winter), and it also doesn't solve the problem Dan's seeing that too much of the soil respiration is heterotrophic.

On the wood flux issue, there should just be an explicit sapwood maintenance respiration. I've never understood why we don't have one.

Finally, if we're going to partition growth respiration by pool, as a first pass we might do this in proportion to the actual amount of growth occurring in each. Indeed, I'd been hoping to propose a variant where we set different growth respiration parameters for leaves, wood, and fine roots based on tissue structural chemistry, but the undergrad working on that project graduated last year and it's been slow progress since then [FYI, the tissues do have non-trivial differences in growth respiration because of different protein and lignin contents].  That said, there are a number of other physiological processes besides growth that are traditionally lumped in with growth respiration because they're thought to be more proportional to GPP than to biomass -- things like the costs of phloem loading and nutrient uptake. The latter is non-trivial and would likewise increase the autotrophic portion of root respiration. As much as I love digging into the physiology, I do worry about the fact that doing so would increase the number of parameters and there's not enough data to constrain them (and probably not enough time/interest from the group since I don't get the impression that anyone sees this as one of our major errors).

If we take Dan's suggestion and partition Rg or Rs by biomass, then it should just be the live biomass, since Bdead plays no role in either.

FYI here are some relevant papers on respiration and storage

Amthor, J. (2000). The McCree–de Wit–Penning de Vries–Thornley Respiration Paradigms: 30 Years Later. Ann. Bot., 86, 1–20.

Cannell, M. & Thornley, J.H.M. (2000). Modelling the Components of Plant Respiration: Some Guiding Principles. Ann. Bot., 85, 45–54.

Dietze, M.C., Sala, A., Carbone, M.S., Czimczik, C.I., Mantooth, J.A., Richardson, A.D., et al. (2014). Nonstructural Carbon in Woody Plants. Annu. Rev. Plant Biol., 65, 667–87.

Kozlowski, T. (1992). Carbohydrate Sources and Sinks in Woody Plants. Bot. Rev., 58, 107–222.

Thornley, J. & Cannell, M. (2000). Modelling the Components of Plant Respiration: Representation and Realism. Ann. Bot., 85, 55–67.

**Comment by DanielNScott** [comment]
Ok, for now (given that the detailed work is stalled) I'm going to implement the simple growth resp partitioning. Can you tell me (or point me to) the parameter values you're using for hardwood growth respiration?

**Comment by mdietze** [comment]
This is the prior we're using for growth respiration https://www.betydb.org/priors/57  The mean's set to 1/3 but it's pretty broad.

**Comment by DanielNScott** [comment]
This issue has been effectively fixed as a result of merging #98 and #127, assuming people use the correct ED2IN options, so I'm closing it.
